### ISSUE TITLE
Add the `opengl` library

### ISSUE THREAD

**Issue by BrandonPacewic** [TigardHighGDC/Ionic#17]
OpenGL C++, is the gui library that we will be using.

I looked into making our own renderer but it would actually take years so this is the best option.

Should be quick and easy

**Comment by BrandonPacewic** [comment]
@Galaxy25 if you have time to make a case for the other gui library we were talking about that would be great. I still am committed to making this engine with as little code from others as possible, using a more advanced library takes a step away from that unless there is a good reason for it. Let me know!

**Comment by BrandonPacewic** [comment]
Also I'm not so sure that this will be easy anymore

**Comment by Galaxy25** [comment]
OpenGL:
More Documentation
Older
More Control

BGFX:
Cross Platform
Light Weight

I'm leaning towards OpenGL. There's more difference between the graphic APIs than I expected.

**Comment by BrandonPacewic** [comment]
Honestly plain OpenGL not being cross platform might be the killer

**Comment by BrandonPacewic** [comment]
Because OpenGl is cross platform with Windows and Linux (like I now know it is), my vote is for OpenGl. If we decide later on that we need something with more features then we can always switch. What is your vote @Galaxy25?

**Comment by Galaxy25** [comment]
I'm voting on OpenGL @BrandonPacewic

**Comment by BrandonPacewic** [comment]
Awesome!

**Comment by BrandonPacewic** [comment]
We will be using GLFW which is just cross platform opengl.
